DEST := /opt/apps/tgproovl

-include .env

.PHONY: clean install run

all:

.env:
	@echo ".env file was not found, creating with defaults"
	cp .env.dist .env

venv/bin/python:
	virtualenv venv
	./venv/bin/pip install -r requirements.txt

run: venv/bin/python .env
	TGPROOVL_TELEGRAM_TOKEN=$(TGPROOVL_TELEGRAM_TOKEN) \
	TGPROOVL_URL_PATH_PREFIX=$(TGPROOVL_URL_PATH_PREFIX) \
	TGPROOVL_URL_HOST=$(TGPROOVL_URL_HOST) \
	TGPROOVL_CONFIG=$(TGPROOVL_CONFIG) \
	TGPROOVL_DEBUG=$(TGPROOVL_DEBUG) \
	TGPROOVL_BOT_PASSWORD=$(TGPROOVL_BOT_PASSWORD) \
	TGPROOVL_PROOVL_USER=$(TGPROOVL_PROOVL_USER) \
	TGPROOVL_PROOVL_TOKEN=$(TGPROOVL_PROOVL_TOKEN) \
	TGPROOVL_PROOVL_API_PREFIX=$(TGPROOVL_PROOVL_API_PREFIX) \
	TGPROOVL_TELEGRAM_PHONE=$(TGPROOVL_TELEGRAM_PHONE) \
	TGPROOVL_SMS_HALF_TIMEOUT=$(TGPROOVL_SMS_HALF_TIMEOUT) \
	TGPROOVL_CHAT_HALF_TIMEOUT=$(TGPROOVL_CHAT_HALF_TIMEOUT) \
	TGPROOVL_TELEGRAM_DEVELOPER=$(TGPROOVL_TELEGRAM_DEVELOPER) \
	TGPROOVL_TELEGRAM_OWNER=$(TGPROOVL_TELEGRAM_OWNER) \
	TGPROOVL_TELEGRAM_API_ID=$(TGPROOVL_TELEGRAM_API_ID) \
	TGPROOVL_TELEGRAM_API_HASH=$(TGPROOVL_TELEGRAM_API_HASH) \
	TGPROOVL_TDLIB_PATH=$(TGPROOVL_TDLIB_PATH) \
	TGPROOVL_TDLIB_ENCRYPTION_KEY=$(TGPROOVL_TDLIB_ENCRYPTION_KEY) \
	TGPROOVL_TDLIB_FILES_DIRECTORY=$(TGPROOVL_TDLIB_FILES_DIRECTORY) \
	TGPROOVL_PERSISTENCE_PATH=$(TGPROOVL_PERSISTENCE_PATH) \
		./venv/bin/python ./tgproovl/app.py

clean:
	rm -rf venv

install:
	virtualenv $(DEST)
	$(DEST)/bin/pip install -r requirements.txt
	$(DEST)/bin/python setup.py install
