image: "leandr/tgproovl"
imagePullSecrets: "regcred"
tag: "0.0.3"
host: "0.0.0.0"
port: 8080
servicePort: 8080
urlPathPrefix: "/tgproovl/"
urlHost: "bot.example.com"
urlScheme: "https"
config: "tgproovl.config.MainConfig"
mountPoint: "/mnt"
pvcSize: "2Gi"
persistencePath: "/mnt/tgproovl.state"
secretKey: ""
botPassword: ""
proovlUser: "proovl-login"
proovlToken: ""
proovlTariff: 2
proovlApiPrefix: "https://www.proovl.com/api/"
telegramToken: ""
telegramDeveloper: -1
telegramOwner: -1
telegramApiId: 1
telegramApiHash: ""
telegramPhone: 02
smsHalfTimeout: 900
chatHalfTimeout: 3600
tdlibPath: "/usr/lib/libtdjson.so.1.5.1"
tdlibEncryptionKey: ""
tdlibFilesDirectory: "/mnt/.tdlib_files/02/"
