apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tgproovl-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvcSize }}
  storageClassName: local-storage
